### ISSUE TITLE
Disable hsplit/vsplit keybinds

### ISSUE THREAD

**Issue by neonvoidx** [DavidRR-F/quick_domains.wezterm#11]
how can i disable the keybinds, not just change them

**Comment by DavidRR-F** [comment]
Currently the default binds are automatically set if you have not overridden in the configuration:

```lua
keys = {
    attach = {
      mods = 'CTRL',
      key = 'd',
      tbl = '',
    },
    vsplit = {
      mods = 'CTRL',
      key = 'v',
      tbl = '',
    },
    hsplit = {
      mods = 'CTRL',
      key = 'h',
      tbl = '',
    },
```

For now you should be able to set the ones you don't want to blanks. This will still set a keybind, but it will be invalid and not overlap with other keybinds you have in place

```lua
    hsplit = {
      mods = '',
      key = '',
      tbl = '',
    },
```

I will be making an update in the future that allows users to just reference the functions in their own keymap config rather than the apply configuration.
